# Generated by Django 5.2.2 on 2025-06-08 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_alter_item_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='vegeterian',
            new_name='vegetarian',
        ),
    ]
