# Generated by Django 5.2.2 on 2025-06-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_rename_vegeterian_item_vegetarian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.URLField(default='https://shorturl.at/AtK4L', max_length=400),
        ),
    ]
